//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroomServiceWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BroomServiceEntities : DbContext
    {
        public BroomServiceEntities()
            : base("name=BroomServiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AboutU> AboutUs { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<ContactU> ContactUs { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<JobRequestCheckList> JobRequestCheckLists { get; set; }
        public virtual DbSet<JobRequestRefImage> JobRequestRefImages { get; set; }
        public virtual DbSet<JobRequestSubSubCategory> JobRequestSubSubCategories { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Property> Properties { get; set; }
        public virtual DbSet<RejectJobRequest> RejectJobRequests { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<SubCategory> SubCategories { get; set; }
        public virtual DbSet<SubSubCategory> SubSubCategories { get; set; }
        public virtual DbSet<TempJobRequest> TempJobRequests { get; set; }
        public virtual DbSet<TempJobRequestCheckList> TempJobRequestCheckLists { get; set; }
        public virtual DbSet<TempJobRequestRefImage> TempJobRequestRefImages { get; set; }
        public virtual DbSet<TempJobRequestSubSubCategory> TempJobRequestSubSubCategories { get; set; }
        public virtual DbSet<TermsCondition> TermsConditions { get; set; }
        public virtual DbSet<Testimonial> Testimonials { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserChat> UserChats { get; set; }
        public virtual DbSet<UserJobReview> UserJobReviews { get; set; }
        public virtual DbSet<UserReview> UserReviews { get; set; }
        public virtual DbSet<UserSubCategory> UserSubCategories { get; set; }
        public virtual DbSet<JobRequest> JobRequests { get; set; }
        public virtual DbSet<PrivacyPolicy> PrivacyPolicies { get; set; }
    }
}
