//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroomServiceWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobRequest()
        {
            this.JobRequestCheckLists = new HashSet<JobRequestCheckList>();
            this.Notifications = new HashSet<Notification>();
            this.Notifications1 = new HashSet<Notification>();
            this.RejectJobRequests = new HashSet<RejectJobRequest>();
            this.TempJobRequestSubSubCategories = new HashSet<TempJobRequestSubSubCategory>();
            this.UserJobReviews = new HashSet<UserJobReview>();
            this.JobRequestSubSubCategories = new HashSet<JobRequestSubSubCategory>();
            this.JobRequestRefImages = new HashSet<JobRequestRefImage>();
        }
    
        public long Id { get; set; }
        public Nullable<long> PropertyId { get; set; }
        public Nullable<long> CategoryId { get; set; }
        public Nullable<long> SubCategoryId { get; set; }
        public Nullable<System.DateTime> JobStartDatetime { get; set; }
        public Nullable<System.DateTime> JobEndDatetime { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> ServiceProviderId { get; set; }
        public Nullable<int> JobStatus { get; set; }
        public Nullable<decimal> QuotePrice { get; set; }
        public Nullable<bool> IsQuoteApproved { get; set; }
        public Nullable<System.DateTime> TimerStartTime { get; set; }
        public Nullable<System.DateTime> TimerEndTime { get; set; }
        public Nullable<int> PaymentMethod { get; set; }
        public Nullable<bool> IsPaymentDone { get; set; }
        public Nullable<decimal> ClientQuotePrice { get; set; }
        public Nullable<bool> HasPrice { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobRequestCheckList> JobRequestCheckLists { get; set; }
        public virtual User User { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        public virtual SubCategory SubCategory1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RejectJobRequest> RejectJobRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TempJobRequestSubSubCategory> TempJobRequestSubSubCategories { get; set; }
        public virtual SubCategory SubCategory2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserJobReview> UserJobReviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobRequestSubSubCategory> JobRequestSubSubCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobRequestRefImage> JobRequestRefImages { get; set; }
        public virtual Property Property { get; set; }
        public virtual Property Property1 { get; set; }
    }
}
