//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroomServiceWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Property()
        {
            this.TempJobRequests = new HashSet<TempJobRequest>();
            this.TempJobRequests1 = new HashSet<TempJobRequest>();
            this.JobRequests = new HashSet<JobRequest>();
            this.JobRequests1 = new HashSet<JobRequest>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public Nullable<bool> ShortTermApartment { get; set; }
        public Nullable<int> FloorNumber { get; set; }
        public Nullable<int> ApartmentNumber { get; set; }
        public string BuildingCode { get; set; }
        public string AccessToProperty { get; set; }
        public Nullable<int> NoOfBathrooms { get; set; }
        public Nullable<int> NoOfQueenBeds { get; set; }
        public Nullable<int> NoOfDoubleBeds { get; set; }
        public Nullable<int> NoOfSingleBeds { get; set; }
        public Nullable<int> NoOfSingleSofaBeds { get; set; }
        public Nullable<int> NoOfDoubleSofaBeds { get; set; }
        public string DuvetSize { get; set; }
        public Nullable<int> NoOfDuvet { get; set; }
        public Nullable<int> NoOfPillows { get; set; }
        public Nullable<bool> Doorman { get; set; }
        public Nullable<bool> Parking { get; set; }
        public Nullable<bool> Balcony { get; set; }
        public Nullable<bool> Dishwasher { get; set; }
        public Nullable<bool> Pool { get; set; }
        public Nullable<bool> Garden { get; set; }
        public Nullable<bool> Elevator { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<int> NoOfToilets { get; set; }
        public Nullable<int> NoOfBedRooms { get; set; }
        public string Size { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TempJobRequest> TempJobRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TempJobRequest> TempJobRequests1 { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobRequest> JobRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobRequest> JobRequests1 { get; set; }
    }
}
