//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroomServiceWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempJobRequestSubSubCategory
    {
        public long Id { get; set; }
        public Nullable<long> SubSubCategoryId { get; set; }
        public Nullable<long> TempJobRequestId { get; set; }
    
        public virtual SubSubCategory SubSubCategory { get; set; }
        public virtual JobRequest JobRequest { get; set; }
    }
}
